FROM node:20

ENV MONGODB_CONNECTION_PROTOCOL mongodb+srv
ENV MONGODB_DB_NAME gha-demo1
ENV PORT 3000

ENV MONGODB_CLUSTER_ADDRESS ""
ENV MONGODB_USERNAME ""
ENV MONGODB_PASSWORD ""

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD ["npm", "start"]