name: Deployment (Container)
on:
  push:
    branches:
      - master
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container:
      image: node:20
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb+srv
      MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CONNECTION }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Build image
        run: docker build -t my-app .
      - name: Run container with secrets
        env:
          MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CONNECTION }}
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: |
          docker run -d \
            -e MONGODB_CLUSTER_ADDRESS=$MONGODB_CLUSTER_ADDRESS \
            -e MONGODB_USERNAME=$MONGODB_USERNAME \
            -e MONGODB_PASSWORD=$MONGODB_PASSWORD \
            -e MONGODB_CONNECTION_PROTOCOL=mongodb+srv \
            -e MONGODB_DB_NAME=${{ env.MONGODB_DB_NAME }} \
            -e PORT=3000 \
            -p 3000:3000 \
            my-app